title: Blogsend Blog
email: blog@blogsend.io
description: Blogsend.io's blog to help you succeed at blogging
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.blogsend.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tryblogsend

permalink: /:year-:month-:day/:title
paginate: 10

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
