title: Blogsend Blog
email: blog@blogsend.io
description: Blogsend.io's blog to help you succeed at blogging
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.blogsend.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tryblogsend

permalink: /:year-:month-:day/:title
paginate: 10

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock

authors:
  mtimofiiv:
    full_name: Mike Timofiiv
    twitter: mtimofiiv
    homepage: https://blogsend.io
    email: mike@blogsend.io
  trinalaropez:
    full_name: Tina Rogers
    twitter: tinarogers
